language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build || true
deploy:
  deploy:
    provider: heroku
    app: retail-fe
    on: main
  api_key:
    secure: grWuc89fk4Hd30s/Xy8dJKE8wUZX20HQs5x+KyqnsaU8eScieqhCowNF2c4pb+KmCvfuWz7W8QULe5yhziwJzfN25a/yf50RcLYzBPwhXaDD5ctcMLyHXrvf1xEcP7aRdhHoxlI8FD9q6yXTaV+urMNMkUQoXGXXksDMrjhAHshEgrQpDGVrFu+L9Ca3asdQZAlQoUpzSsIiwJXj2ZK88IW7K935AV0fU1MS7RK7EgEf4g3DE8wEA3x6sz3t1cog4ZZiYLypFrBG2iVJQJy1d+YYVbmqYFGtYUGbIKqy0r9WXxzUSYjAEY0vSxw582rhlkgqIXZCwVGBJnAKrrycN5NaQnft2zsbJPI3CbepxqVk3LYqmPNMNyPyRIKmcsJSBwWs0XZ7g8JlvQ0FD51MSH2zxZ8IqhHPNcGucHaALlofHE1GHP3U8zDktNQiGp44hacJdiQKaL4wzmwc4FIx0mBT08eEuirfUhs9gWa3QYkOWqJgnyL+FIw32A6SoSdSwpyEaSWcxWUHwPy6z5DRh2Vrw3iF8H1TV0QkV2olS7BaFrYouQIedhGSu793cYKD3EGkjfO5oZupKzalX9e/evUZ6KITZBr3Hqv21Eak6AFhRcXA1SSDstlwVT2OmQme0eLvuWE1UrnxJkP5V8A940rWHuT4TXKHL3Ct33x/Jy0=
